config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  devise_for :users, skip: [:registrations], controllers: { omniauth_callbacks: 'devise/omniauth' }

  namespace :users do
    resources :posts, only: :index
  end

  resources :posts do
    resources :bookmarks, only: %i[create]
    resources :votes, only: :create, module: 'posts'
  end

  namespace :bookmarks do
    resources :posts, only: %i[index]
  end

  resources :bookmarks, only: %i[destroy]
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash flash--<%= type %>">
    <div class="message">
      <% if message.kind_of?(Array) %>
        <ul>
          <% message.each do |msg|%>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% else %>
        <%= message %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <small>
    <p> Made with ❤️ by <%= link_to 'b0rdjack', 'https://github.com/b0rdjack', target: '_blank' %> and <%= link_to 'phanremy', 'https://github.com/phanremy', target: '_blank' %></p>
  </small>
</footer>

app/views/shared/_header.html.erb
<header>
  <h1> CheatCheet </h1>
  <br>
  <p> Tricky questions, easy answers 🤙 </p>
  <nav>
    <%= link_to 'Home', root_path, class: 'nav-current' %>
    <%= link_to 'About', 'https://github.com/CheatCheet/cheatcheet', target:'_blank' %>
    <% if user_signed_in? %>
      <%= link_to 'My posts', users_posts_path%>
      <%= link_to 'My bookmarks', bookmarks_posts_path %>
      <%= link_to 'New post', new_post_path %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path %>
    <% end %>
  </nav>
</header>

app/views/shared/_return_to_top.html.erb
<div id="return-to-top"
     data-controller="return-to-top"
     data-action="scroll@window->return-to-top#onScroll">
  <button data-action="click->return-to-top#proceed"> Return to top <i class="fas fa-level-up-alt"></i> </button>
</div>