config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  devise_for :users, skip: [:registrations], controllers: { omniauth_callbacks: 'devise/omniauth' }

  namespace :users do
    resources :posts, only: :index
  end

  resources :posts do
    resources :bookmarks, only: %i[create]
    resources :votes, only: :create, module: 'posts'
  end

  namespace :bookmarks do
    resources :posts, only: %i[index]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/concerns/posts/pagination.rb
# frozen_string_literal: true

# REF: https://www.beflagrant.com/blog/pagination-with-hotwire
module Posts
  module Pagination
    extend ActiveSupport::Concern

    def set_paginated_posts
      @pagy, @posts = pagy(@posts, items: 25)
    end
  end
end

app/models/concerns/posts/set_bookmarks.rb
# frozen_string_literal: true

module Posts
  module SetBookmarks
    extend ActiveSupport::Concern

    def set_bookmarks
      @bookmarks = current_user&.bookmarks
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user
  belongs_to :stack

  has_rich_text :body
  has_one :action_text_rich_text, class_name: 'ActionText::RichText', as: :record, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :title, length: { minimum: 5 }
  validates :body, length: { minimum: 5 }

  default_scope { order(created_at: :desc) }
  scope :from_user, ->(id) { where('user_id = ?', id) }
  scope :from_stack, ->(stack_name) { includes(:stack).where(stack: { name: stack_name }) }
  scope :bookmarked, ->(user_id) { includes(:bookmarks).where(bookmarks: { user_id: user_id }) }
  scope :related_to, lambda { |value|
                       joins(:action_text_rich_text, :stack).where("posts.title ILIKE '%#{value}%' OR
                      action_text_rich_texts.body ILIKE '%#{value}%' OR stacks.name ILIKE '%#{value}%'")
                     }

  def self.with_all_inclusions
    includes(:stack).with_rich_text_body
  end

  def bookmark_id(bookmarks)
    return unless bookmarks

    bookmarks.where(post: self).first&.id
  end
end

app/controllers/bookmarks/posts_controller.rb
# frozen_string_literal: true

module Bookmarks
  class PostsController < ApplicationController
    include Posts::Pagination
    include Posts::SetBookmarks

    load_and_authorize_resource
    before_action :authenticate_user!

    def index
      @posts = Post.with_all_inclusions.bookmarked(current_user)
      set_paginated_posts
      set_bookmarks
    end
  end
end

app/controllers/posts/votes_controller.rb
# frozen_string_literal: true

module Posts
  class VotesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      post_params[:vote] == 'up' ? current_user.up_votes(@post) : current_user.down_votes(@post)
    end

    private

    def post_params
      params.require(:post).permit(:vote)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include Posts::Pagination
  include Posts::SetBookmarks

  load_and_authorize_resource

  before_action :set_post, except: %i[index new create]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @posts = Post.with_all_inclusions.accessible_by(current_ability)
    @posts = posts_query(@posts)
    set_paginated_posts
    set_bookmarks
  end

  # TODO: set post bookmark id
  def show; end

  def edit; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Post successfully created'
      redirect_to @post
    else
      flash.now[:error] = @post.errors.full_messages
      render_flash
    end
  end

  def update
    if @post.update(post_params)
      flash.now[:success] = 'Post was successfully updated'
      redirect_to @post
    else
      flash.now[:error] = @post.errors.full_messages
      render_flash
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = 'Post was successfully deleted.'
      redirect_to posts_path
    else
      flash.now[:error] = 'Something went wrong'
      render_flash
    end
  end

  private

  def posts_query(posts)
    posts = posts.from_user(params[:user_id]) if params[:user_id]
    posts = posts.related_to(params[:search]) if params[:search]
    posts = posts.from_stack(params[:stack]) if params[:stack]

    posts
  end

  def post_params
    params.require(:post).permit(:title, :body, :public, :stack_id, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users/posts_controller.rb
# frozen_string_literal: true

module Users
  class PostsController < ApplicationController
    include Posts::Pagination
    include Posts::SetBookmarks

    # load_and_authorize_resource ?
    # REF: https://stackoverflow.com/questions/30840231/cancan-explanation-of-load-and-authorize-resource
    before_action :authenticate_user!

    def index
      @posts = Post.with_all_inclusions.from_user(current_user.id)
      set_paginated_posts
      set_bookmarks
    end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  include Pagy::Frontend

  def build_posts_url(page:)
    url_for(only_path: false,
            params: { page: page }.merge(request.query_parameters.except(:page)))
  end

  def created_at_date(post)
    post.created_at.strftime('%b %d, %Y')
  end

  def stack_collection(stack_id)
    options = Stack.order(:name).pluck(:name, :id)
    options_for_select(options, stack_id || Stack.default.id)
  end
end

app/views/posts/_collection.html.erb
<% if infinite_scroll %>
  <%= turbo_frame_tag :posts do %>
    <%= render collection: @posts, partial: 'posts/post' %>
    <% if @pagy.next %>
      <%= turbo_frame_tag :posts, loading: :lazy, src: build_posts_url(page: @pagy.next) do %>
        <div class="spinner-container">
          <i class="fas fa-circle-notch fa-spin"></i>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%= render collection: @posts, partial: 'posts/post' %>
  <%== pagy_nav(@pagy) %>
<% end %>

app/views/posts/_form.html.erb
<%= turbo_frame_tag 'post_form' do %>
  <%= form_for post, data: { "turbo-frame" => "_top" } do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'w-100' %>
    </div>
    <div class="field">
      <%= f.select :stack_id, stack_collection(post.stack_id), {}, { data: { 'controller': 'slim-select', addable: false } } %>
    </div>
    <div class="field">
      <%= f.label :body %>
      <%= f.rich_text_area :body %>
    </div>
    <div>
      <%= f.label :public %>
      <%= f.check_box :public %>
    </div>
    <div class="field">
      <%= f.hidden_field :user_id, value: current_user&.id %>
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class="post">
    <div class="post__header">
      <h2><%= link_to post.title, post_path(post), target: '_top' %></h2>
      <%= turbo_frame_tag "bookmark_options_for_post_#{post.id}" do %>
        <%= render 'bookmarks/bookmark_options', post: post, user: current_user, bookmarks: @bookmarks %>
      <% end %>
    </div>
    <div class='post__meta'><em><%= created_at_date(post) %></em></div>
    <div class="post__body">
      <%= render partial: 'posts/votes/vote', locals: { post: post } %>
      <div class='post__content'>
        <%= post.body %>
      </div>
    </div>
    <%= link_to posts_url(stack: post.stack.name), target: '_top' do %>
      <button class="stack__button">
        <%= post.stack.name %>
      </button>
    <% end %>
  </div>
<% end %>

app/views/posts/_search.html.erb
<div class="search">
  <%= form_with url: posts_path, method: :get do |form| %>
    <%= form.text_field :search, value: params[:search], placeholder: 'Search a term (Ruby on Rails, gem devise, etc.)' %>
  <% end %>
</div>

app/views/posts/_search_bar.html.erb
<div class="search">
  <%= form_with url: posts_path do |form| %>
    <%= form.text_field :filter, placeholder: 'Search a term (Ruby on Rails, gem devise, etc.)' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, post_tags: @post_tags %>

app/views/posts/index.html.erb
<% if @posts.count.zero? %>
  <p>No Posts</p>
<% else %>
  <%= render 'search' %>
  <%= render 'collection', infinite_scroll: infinite_scroll_on_current_page? %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post, post_tags: @post_tags %>

app/views/posts/show.html.erb
<% if user_signed_in? %>
  <div class="post__actions">
    <% if @post.user == current_user %>
      <%= link_to t('.edit'), edit_post_path %>
    <% end %>
    <% if can? :manage, @post %>
      <%= link_to t('.delete'), post_path, method: :delete, data: { confirm: t('.confirm_delete') } %>
    <% end %>
  </div>
<% end %>
<%= render @post %>